TERMUX_PKG_HOMEPAGE="https://github.com/therealkenc/libudev-stub"
TERMUX_PKG_DESCRIPTION="A libudev stub and proxy library for WSL"
TERMUX_PKG_LICENSE="LGPL-2.1"
TERMUX_PKG_MAINTAINER="xMem <haooy@outlook.com>"
TERMUX_PKG_VERSION="1.0.4"
TERMUX_PKG_SRCURL="git+https://github.com/therealkenc/libudev-stub.git"
TERMUX_PKG_CONFLICTS="libudev"
